### ISSUE TITLE
item render Reborn 

### ISSUE THREAD

**Issue by Darkslayer99-beep** [jredfox/iitemrenderer#19] opened 2024-10-21 13:50 UTC
Don't know what to do, as the mod mess up lucraft, and I don't know how to config that to work with lucraft

**Comment by jredfox** [comment] 2024-10-21 16:59
> work

post a proper bug report. What happens, crash report, log file `.minecraft/logs/log.txt` where log.txt is the latest and you can find the latest by filtering by date modified and finding the latest log file. saying "it messes it up" doesn't help

**Comment by jredfox** [comment] 2024-10-21 21:16
Unable to reproduce will be closed in 24hrs if you don't specify what the actual issue is. I download both the coremod and the addon with no issues

**Comment by Darkslayer99-beep** [comment] 2024-10-21 23:14
fine, newest version breaks certain models, and had to down down grade 2, for the models to work right

**Comment by Darkslayer99-beep** [comment] 2024-10-21 23:17
oh, and up dating it to the newest one breaks, the ones that are working in the older versions

**Comment by jredfox** [comment] 2024-10-22 00:05
> oh, and up dating it to the newest one breaks, the ones that are working in the older versions

again really bad bug report. certain models doesn't help. luckfully for you 1 out of 4,000+ possible models I happened to find in just the "core mod" which was really a mod + coremod because it contained actual minecraft content such as items and blocks. The thanos gauntlet is bugged.

This issue is actually caused by something very weird they are doing. When I attempted to add their IBakedModel into the config it still didn't work as the transforms were applied twice yet somehow they were not applied the first time. There are several bugs from this poorly written mod I am sure the same thing happens with codechicken lib required by alot of mods. 

The mod also contained a very poorly written coremod which improper target injections and assumptions on code that may change even between forge builds.

I will look into if I can work around broken Renderer Mods by simply only overriding transforms if it's my item but nothing garenteed as there is no real mapping between IBakedModel & Item at least not yet

**Closed as completed by jredfox** 2024-10-22 00:05 UTC

**Comment by Darkslayer99-beep** [comment] 2024-10-22 00:42
thank you

**Comment by jredfox** [comment] 2024-10-22 22:04
pre7.0 of IItemRenderer should fix this issue. Report any new bugs this includes what the bug is and steps to reproduce it (what happened). This update contains breaking changes and may not work with all mods that depend upon it unlike silkspawners which simply works
